var levels = [{
  speed: 1.5,
  title: 'Lift',
  map: '\
  xxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\
  xxxxx.xxxxxxxx....xxxxxxxxxxxxxxxxxxxxxx\
  xxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\
  xxxxx.xxxxxxxx....x.xxx.x.xxx.x....x.xxx\
  xxxx...xxxxxxx.xx.x..xx.x..xx.x.xxxx.xxx\
  xxx.....xxxxxx.xx.x.x.x.x.x.x.x...xx.xxx\
  xx.......xxxxx.xx.x.xx..x.xx..x.xxxxxxxx\
  x.........xxxx....x.xxx.x.xxx.x....x.xxx\
  ..........xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\
  ..........xxxxxxxxxxxxxx................\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.x....xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx.x.xx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxx...xx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxx.......xxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxx......xxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxx...xxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxx\
  xxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxx\
  '
}, {
  speed: 0.3,
  title: 'Lift',
  map: '\
  xxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxx\
  x.x.x.x.x.x.x.x.x.x.x.x.x..xx..........x\
  x........................x.xx.xxxxxxxx.x\
  x........................x.xx.x........x\
  x........................x....x.xxxxxx.x\
  x........................x.xxxx.x......x\
  x........................x.x....x.xxxx.x\
  x........................x.x.xxxx.xxxx.x\
  x........................x.x.x....xxxx.x\
  x........................x.x.x.xxxxxxx.x\
  x........................x.x.x.xxxxxxx.x\
  x........................x.x.x.xxxxxxx.x\
  x........................x.x.x.xxxxxxx.x\
  xx.x.x...................x.x.x.xxxxxxx.x\
  ......x..................x.x.x.xxxxxxx.x\
  ......x..................x.x.x.xxxxxxx..\
  .......x.xx.xx...........x.x.x.xxxxxxxxx\
  ....x.x.......x..........x.x.x.xxxxxxxxx\
  xxxxx...xxxxx.x..........x.x.x.xxxxxxxxx\
  xxxxx...xxxxx.x..........x.x.x.xxxxxxxxx\
  xxxxx...xxxxx..x.x.x.xx.xx.x.x.xxxxxxxxx\
  xxxxx...xxxxx.x......x.xxx.x.x.xxxxxxxxx\
  xxxxx...xxxxx.xx.xxx....xx.x.x.xxxxxxxxx\
  xxxxx...xxxxx.xx.x.xxxx.xxxxxxxxxxxxxxxx\
  xxxxx...xxxx.....x................xxxxxx\
  xxxxx...xxxxxxxx.xxxxxx.xxxx.xxxxxxxxxxx\
  xxxxx...xxxxxxxx...x.....xx..xxxxxxxxxxx\
  xxxx....xxxxxxxxxx.xxxxxxxx....xxxxxxxxx\
  ...xx...xxxxxx.....xxxxxxxx..x..xxxxx..x\
  .....xxxxxxxxxxxxx.xxxxxxxxxx..xxxxxxx..\
  xxx..........xxx...xxxxxxxxx..x....xxxxx\
  ...xxxxxxxxx...xxxxxxxxxxxxx....x..xxxxx\
  ............x......xxxxxxxxxxxxxxx......\
  xxxxxxxxxxx..xxxxx..xxxxxxxxxxx....x..xx\
  xxxxxxxx...x......x.....xxxxxx.x.xxxxx.x\
  ..xxxxxx.xx.xxxx.xxxxxxx.xxxxx.xx.......\
  x.xxxxx.....xxxx.xxxxxxx.xxxxx.....x.xxx\
  x......xxx..xxxx.x.xxx.x.xxx.xxxx.x..xxx\
  xxxx......x.xxxx.x.xxx....xx.xxxx.xxxxxx\
  ...x.xxxxxx......x.xxx.xx.xx.xxxx.x.....\
  xx.x.......xxxx.x............xxxx.xxxxxx\
  x..xxx.xxxxxxxx.xxxx.xxxxxxx...xx.xxxxxx\
  ....xx........x......x.......x.....xxxxx\
  .x..xx.xx.x.x.xxxxxx.x.xxxxx.x.xxxxxxxxx\
  .xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxx\
  '
}, {
  speed: 0.3,
  title: 'Lift',
  map: '\
  xxx..xxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxx..\
  xxxx.xxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxx..\
  xxx.xxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxx..\
  ..........................xxxx.xxxxxxx..\
  ...x.......................xxx.xxxxxxx..\
  xxx.xxxxxxxxxxxxxxxxxxxxxx..xx.xxxxxxx..\
  xxx.x.xxx...x.xxxxxxxxxxxx...x.xxxxxxx..\
  xxx.x.xxx.x.x.xxxxxxxxxxxx.x.x.xxxxxxx..\
  xxx.x...x...x...xxxxxxxxxx.x.x.xxxxxxx..\
  xxx.xxxxxxxxxxxxxxxxxxxxxx.x.x.xxxxxxx..\
  xxx.xxxxxxxxxxxxxxxxxxxxxx.x.x.xxxxxxx..\
  xxx.xxxxxxxxxxxxxxxxxxxxxx.x.x.xxxxxxx..\
  xxx.xxxxxxxxxxxxxxxxxxxxxx.x.x.xxxxxxx..\
  xxx.xxxxxxxxxxxxxxxxxxxxxx.x.x.xxxxxxx..\
  xxx.xxxxxxxxxxxxxxxxxxxxxx.x...xxxxxxx..\
  xxx..xxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxx..\
  xxx..xxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxx..\
  xxx..xxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxx..\
  xxx..xxxxxxxxxxxxxxxx...xx.xxxxxxxxxxx..\
  xxx..xxxxxxxxxxxxxx...x.xx.xxxxxxxxxxx..\
  xxx.....x..xxxxxx...xxx....xxxxxxxxxxx..\
  xx..xx...x.xxxxx..xxxxxxxxxxxxxxxxxxxx..\
  xxx..xx..xxxxxxxx...xxxxxxxxxxxxxxxxxx..\
  x...............xxx.xxxxxxxxxxxxxxxxxxxx\
  x.xxxxx..xx.xxx...x.xxxxxxxxxxxxxxxxxx..\
  x.....x..xx...x.x.x.xxxxxxxxxxxxxxxxxx..\
  .xxxx.x..x..x.x...x.xxxxxxxxxxxxxxxxxx..\
  x....xx..x.x.x..x...xxxxxxxxxxxxxxxxxx..\
  ..xx.xx..xx.xx..xxxxxxxxxxxxxxxxxxxxxx..\
  xxxx.x...x.x.x..xxxxxxxxxxxxxxxxxxxxxx..\
  xxxx.x.x.......xxxxxxxxxxxxxxxxxxxxxxx..\
  xxxx...x.xxxxxxxxxxxxxxxxxxxxxxxxxxxxx..\
  xxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxx..\
  xxxxxxxx...xxxxxxxxxxxxxxxxxxxxxxxxxxx..\
  ..xxxxxxx...xxxxxxxxxxxxxxxxxxxxxxxxxx..\
  ...xxxxxxx..xxxxxxxxxxxxxxxxxxxxxxxxxxxx\
  ..xxxxxxxxx.xxxxxxx...xxxxxxxxxxxxxxxxx.\
  xxxxxxxxxxxx....xx...xxxxxx.............\
  xxxxxxxxx....xx......xxxxx..xxxxxxxxxxxx\
  xxxxxxxx..xxxxxxxxxxxxxxxx........xxxxxx\
  xxxxxx...............xxxxxxxxxxxx..xxxxx\
  xxxx....xxxxxxxxxxxx....xxx........xxxxx\
  xx...xxxxxxxxxxx.....xxxx...xxxxxxxxxxxx\
  xxxx....xxxxxx....xxxxx...xxxxxxxxxxxxxx\
  xxxxxxx....xxxxxx....xxxx...xxxxxxxxxxxx\
  xxxxx....xxxxxx....xxxxxxxx...xxxxxxxxxx\
  xxxxxx.....xxxxxx......xxxxxx.....xxxxxx\
  ........................................\
  ...............................x........\
  ..............................xxx.......\
  .............................xxxxx......\
  ...............................x........\
  ...............................x........\
  ...............................x........\
  '
}, {
  speed: 2.5,
  title: 'Lift',
  map: '\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x..xxxxxxxxx....xxxxxxxxxx.x\
  xx.xxxxxxxxx....xxxxxxxxxx.x\
  x..xxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx.............x.x\
  x.xxxxxxxxxx.............x.x\
  x.xxxxxxxxxxxxxxxxxxx....x.x\
  x.x......................x.x\
  x.x......................x.x\
  x.x....xxxxxxxxxxxxxxxxxxx.x\
  x.x....xxxxxxxxxxxxxxxxxxx.x\
  x.x....xxxxxxxxxxxxxxxxxxx.x\
  x.x....xxxxxxxxxxxxxxxxxxx.x\
  x.x....xxxxxxxxxxxxxxxxxxx.x\
  x.x....xxxxxxxxxxxxxxxxxxx.x\
  x.x....xxxxxxxxxxxxxxxxxxx.x\
  x.x....xxxxxxxxxxxxxxxxxxx.x\
  x.x....xxxxxxxxxxxxxxxxxxx.x\
  x.x....xxxxxxxxxxxxxxxxxxx.x\
  x.x....xxxxxxxxxxxxxxxxxxx.x\
  x.x....xxxxxxxxxxxxxxxxxxx.x\
  x.x....xxxxxxxxxxxxxxxxxxx.x\
  x.x....xxxxxxxxxxxxxxxxxxx.x\
  x.x....xxxxxxxxxxxxxxxxxxx.x\
  x.x....xxxxxxxxxxxxxxxxxxx.x\
  x.x....xxxxxxxxxxxxxxxxxxx.x\
  x.x....xxxxxxxxxxxxxxxxxxx.x\
  x.x....xxxxxxxxxxxxxxxxxxx.x\
  x.x....xxxxxxxxxxxxxxxxxxx.x\
  x.x......................x.x\
  x.x......................x.x\
  x.xxxxxxxxxxxxxxxxxxx....x.x\
  x.xxxxxxxxxx.............x.x\
  x.xxxxxxxxxx.............x.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  x.xxxxxxxxxx....xxxxxxxxx..x\
  x.xxxxxxxxxx....xxxxxxxxx.xx\
  x.xxxxxxxxxx....xxxxxxxxx..x\
  x.xxxxxxxxxx....xxxxxxxxxx.x\
  '
}, {
  speed: .6,
  map: '\
  xxxxxxxx..xxxxxxxxxxxxxxxxxx\
  xxxxxxx..xxxxxxxxxxxxxxxxxxx\
  xxxxxx..xxxxxxxxxxxxxxxxxxxx\
  xxxxx..xxxxxxxxxxxxxxxxxxxxx\
  xxxx..xxxxxxxxxxxxxxxxxxxxxx\
  xxx..xxxxxxxxxxxxxxxxxxxxxxx\
  xx..xxxxxxxxxxxxxxxxxxxxxxxx\
  x..xxxxxxxxxxxxxxxxxxxxxxxxx\
  x..xxxxxxxxxxxxxxxxxxxxxxxxx\
  ...x........................\
  xxxx..xxxxxxxxxxxxxxxxxxxxxx\
  xxxx..xxxxxxxxxxxxxxxxxxxxxx\
  xxxx..xxxxxxxxxxxxxxxxxxxxxx\
  xxxx..xxxxxxxxxxxxxxxxxxxxxx\
  xxxx..xxxxxxxxxxxxxxxxxxxxxx\
  xxxx..xxxxxxxxxxxxxxxxxxxxxx\
  xxxx..xxxxxxxxxxxxxxxxxxxxxx\
  xxxx..xxxxxxxxxxxxxxxxxxxxxx\
  xxx...xxxxxxxxxxxxxxxxxxxxxx\
  xx....xxxxxxxxxxxxxxxxxxxxxx\
  x.....xxxxxxxxxxxxxxxxxxxxxx\
  ......x.....................\
  xxxxxx......xxxxxxxxxxxxxxxx\
  ...........xxxxxxxxxxxxxxxxx\
  ...........xxxxxx...........\
  xxxxxxxxxxxxxxxxx...........\
  ...........xxxxxx...........\
  ...........xxxxxxxxxxxxxxxxx\
  ...........xxxxxx...........\
  xxxxxxxxxxxxxxxxx...........\
  ...........xxxxxx...........\
  ...........xxxxxx...........\
  ...........xxxxxxxxxxxxxxxxx\
  ...........xxxxxx...........\
  ...........xxxxxx...........\
  ...........xxxxxx...........\
  xxxxxxxxxxxxxxxxx...........\
  ...........xxxxxx...........\
  ...........xxxxxx...........\
  ...........xxxxxxxxxxxxxxxxx\
  '
}, {
  speed: .6,
  map: '\
  xxxxxx..xxxxx..xxxxxxxxxxxxx\
  xxxxx..xxxxx..xxxxxxxxxxxxxx\
  xxxx..xxxxx..xxxxxxxxxxxxxxx\
  xxx..xxxxx..xxxxxxxxxxxxxxxx\
  xx..xxxxx..xxxxxxxxxxxxxxxxx\
  xxx...x...xxxxxxxxxxxxxxxxxx\
  xxxxx.x.xxxxxxxxxxxxxxxxxxxx\
  xxxxx.x.xxxxxxxxxxxxxxxxxxxx\
  xxxxx....xxxxxxxxxxxxxxxxxxx\
  xxxxxxxx..xxxxxxxxxxxxxxxxxx\
  xxxxxx...xxxxxxxxxxxxxxxxxxx\
  xxxxxxxx...xxxxxxxxxxxxxxxxx\
  xxxxxxxxxx.x...xxxxxxxxxxxxx\
  xxxxxxxxxx...x...xxxxxxxxxxx\
  xxxxxxxxxxxxx..xxxxxxxxxxxxx\
  xxxxxxxx...xx..xxxxxxxxxxxxx\
  xxxxxxx..x.....xxxxxxxxxxxxx\
  xxxxxxx..xxxxxxxxxxxxxxxxxxx\
  xxxxxxx..xxxxxxxxxxxxxxxxxxx\
  xxxxxx....xxxxxxxxxxxxxxxxxx\
  xxxxx..xxxxxxxxxxxxxxxxxxxxx\
  xxxxxx...xxxxxxxxxxxxxxxxxxx\
  xxxxxxxx...xxxxxxxxxxxxxxxxx\
  xxxxxx...xxxxxx.....xxxxxxxx\
  xxxxxx..........xxx...xxxxxx\
  xxxxxx.xx.xx.xx.x...xxxxxxxx\
  xxxxxxx..x..x.xx..xxxxxxxxxx\
  xxxxxx.x......xxx....xxxxxxx\
  xxxxxxxxx.xxx.xx..xxxxxxxxxx\
  xxxxx.......x.x.....xxxxxxxx\
  xxxx..x.xx..x.x.xxxxx.x...xx\
  xxx..x.x..x...x.xxxxx.x.xxxx\
  x.....xx.....xx..x......xxxx\
  x.xxxx....x...x....x....xxxx\
  x.xxx..xxxxxx..xxxx..xx.xxxx\
  x..xx....xxxx...xxxx..xxxxxx\
  x..........................x\
  xx.....xxx.....xxxxxx...xxxx\
  x..........................x\
  xxxx......xx..xx........xxxx\
  '
}, {
  speed: .6,
  map: '\
  xxxxxxxxxxxxxxx.xxxxxxxxxxxx\
  xxxxxxxxxxxxx.x.xxxxxxxxxxxx\
  xxxxxxxxxxxxx.x.xxxxxxxxxxxx\
  xxxxxxxxxxxxx.x.xxxxxxxxxxxx\
  xxxxxxxxxxxxx.x.xxxxxxxxxxxx\
  xxxxxxxxxxxx.....xxxxxxxxxxx\
  xxxxxxxxxxxx.xxxxxxxxxxxxxxx\
  xxxxxxxxxxx...xxxxxxxxxxxxxx\
  xxxxxxxxx...xxxxxxxxxxxxxxxx\
  xxxxxxxxx.xxxxxxxxxxxxxxxxxx\
  xxxxxxxxx...xxxxxxxxxxxxxxxx\
  xxxxxxxxxxx...xxxxxxxxxxxxxx\
  xxxxxxxxx...xxxxxxxxxxxxxxxx\
  xxxxxxxx..xxxxxxxxxxxxxxxxxx\
  xxxxxxxx.....xxxxxxxxxxxxxxx\
  xxxxxxxxxxxx...xxxxxxxxxxxxx\
  xxxxxxxxxx...xxxxxxxxxxxxxxx\
  xxxxxxxxxxxx...xxxxxxxxxxxxx\
  xxxxxxxxxxxxxx...xxxxxxxxxxx\
  xxxxxxxxxxxx...xxxxxxxxxxxxx\
  xxxxxxxxxxx..xxxxxxxxxxxxxxx\
  xxxxxxxxxxx.....xxxxxxxxxxxx\
  xxxxxxxxxxxxxxx...xxxxxxxxxx\
  xxxxxxxxxxxxxx..xxxxxxxxxxxx\
  xxxxxxxxxxxxxx...xxxxxxxxxxx\
  xxxxxxxxxxxxxxxx...xxxxxxxxx\
  xxxxxxxxxxxxxxxxxx..xxxxxxxx\
  xxxxxxxxxxxxxxx....xxxxxxxxx\
  xxxxxxxxxxxxxx...xxxxxxxxxxx\
  xxxxxxxxxxxxxxxx...xxxxxxxxx\
  xxxxxxxxxxxxxxxxxx...xxxxxxx\
  xxxxxxxxxxxxxxxx...xxxxxxxxx\
  xxxxxxxxxxxxxx...xxxxxxxxxxx\
  xxxxxxxxxxxx...xxxxxxxxxxxxx\
  xxxxxxxxx..........xxxxxxxxx\
  xxxxxxx...xxx..xxx...xxxxxxx\
  xxxxx...xxxxxx.xxxxx...xxxxx\
  xxx...xxxxxx...xxxxxxx...xxx\
  x...xxxxxxx..xxxxxxxxxxx...x\
  ...xxxxxxxxx..xxxxxxxxxxx...\
  '
}, {
  speed: .7,
  map: '\
  xxxxxxxx.xxxxxxx.xxxxxxxxxxx\
  xxxxxxx..xxxxxx......xxxxxxx\
  xxxxxxx.xxxxxxxxxxxx..xxxxxx\
  xxxxxx..xxxx...........xxxxx\
  xxxxxxx...................xx\
  xxxxxxxx.xxxxxxxxxxxxxxx..xx\
  x....x....x........x......xx\
  x.......x....x.....x.xxxxxxx\
  x...xxxxxxxxxx.x.x.x.....xxx\
  xxx......xxx.......xxxxx..xx\
  x...xxxx.....xxxxx........xx\
  x.........................xx\
  x...xxxx.....xxxxx......xxxx\
  x.........................xx\
  xx.xxxxxx.......xxxxxx.xxxxx\
  x.........................xx\
  xxxxxx......xxxxxxx.xxxxxxxx\
  x.........................xx\
  xxx.xxxxxxxxx.....xxxxx.xxxx\
  x.........................xx\
  xxxxxxxxx.......xxx.xxxxxxxx\
  x.........................xx\
  xxxxxx......xxxxxxxxxx...xxx\
  x.........................xx\
  xxxxxxxxxxxxx.....xxxxxxxxxx\
  '
}, {
  speed: .6,
  map: '\
  xx...........xx............x\
  xxx.........xxxx..........xx\
  xxxx.......xxxxxx........xxx\
  xxxxx.....xxxxxxxx......xxxx\
  xxxxxx...xxxxxxxxxx....xxxxx\
  xxxxxx..xxxxxxxxxxxx..xxxxxx\
  xxxxxx..xxxxxxxxxxxx..xxxxxx\
  xxxxxxx..............xxxxxxx\
  xxxxxxxxxxxxx..xxxxxxxxxxxxx\
  xxxxxxxxxxxx....xxxxxxxxxxxx\
  xxxxxxxxxxxx.xx.xxxxxxxxxxxx\
  xxxxxxxxxx...xx...xxxxxxxxxx\
  xxxxxxxxxx..xxxx..xxxxxxxxxx\
  xxxxxxx....xxxxxx....xxxxxxx\
  xxxxxxx.xxxxxxxxxxxx.xxxxxxx\
  xxxxxxx..............xxxxxxx\
  xxxxxxxxxxxxx..xxxxxxxxxxxxx\
  xxxxxxxxxxxxx..xxxxxxxxxxxxx\
  xxxxxxxxxxxxx..xxxxxxxxxxxxx\
  xxxxxxx....xx..xx....xxxxxxx\
  xxxxxxx.x..xx..xx..x.xxxxxxx\
  xxxxxxx.x..xx..xx..x.xxxxxxx\
  xxxxxxx.x..xx..xx..x.xxxxxxx\
  xxxxxxx.x..xx..xx..x.xxxxxxx\
  xxxxxxx.x..........x.xxxxxxx\
  xxxxxxx.xxxxxxxxxxxx.xxxxxxx\
  xxxxxxx....xxxxxx....xxxxxxx\
  xxxxxxxxxx..xxxx..xxxxxxxxxx\
  xxxxxxxxxx...xx...xxxxxxxxxx\
  xxxxxxxxxxxx.xx.xxxxxxxxxxxx\
  xxxxxxxxxxxx....xxxxxxxxxxxx\
  xxxxxxxxxxxxx..xxxxxxxxxxxxx\
  xxxxxxx..............xxxxxxx\
  xxxxxx..xxxxxxxxxxxx..xxxxxx\
  xxxxxx..xxxxxxxxxxxx..xxxxxx\
  xxxxx....xxxxxxxxxx....xxxxx\
  xxxx......xxxxxxxx......xxxx\
  xxx........xxxxxx........xxx\
  xx..........xxxx..........xx\
  x............xx............x\
  '
}, {
  'speed': .9,
  'map': '\
  .x...x.xxxx.xxxx.x....xxx..\
  .x...x.x..x.x..x.x....x..x.\
  .x.x.x.x..x.xxxx.x....x..x.\
  .xx.xx.x..x.x.x..x....x..x.\
  .x...x.xxxx.x..x.xxxx.xxx..\
  ...........................\
  ...........................\
  .x...x.xxxx.x....x....xxxx.\
  .x...x.x....x....x....x..x.\
  .xxxxx.xxx..x....x....x..x.\
  .x...x.x....x....x....x..x.\
  .x...x.xxxx.xxxx.xxxx.xxxx.\
  '
}];